generate_pattern: True
model: 'bipolar'
pixel_size: 100
pixel_size_suffix: ""
frame_width: 1000
geometry: 'Flat_human'
number_of_diodes: 2
sirof_capacitance: 6
photosensitive_area_edge_to_edge: 92
active_electrode_radius: 17
light_to_current_conversion_rate: 0.4
photosensitive_area: 4075.72
r_matrix_output_file: "R_${geometry}_PS${pixel_size}${pixel_size_suffix}.pkl"
r_matrix_conductivity: 1
Ipho_scaling: 1
Isat: 0.02
ideality_factor: 1.14
shunt_resistance: 790150.0
initial_Vactive: 0
temperature: 37
nominal_temperature: 25
simulation_duration_sec: ~
simulation_resolution_ms: ~
user_files_path: ~
pixel_label_input_file: ~
monopolar:
  - return_to_active_area_ratio: 5.7525
  - r_matrix_simp_ratio: 0.1
bipolar:
  - additional_edges: 142
  - r_matrix_simp_ratio: 0.1
