duration: 9.8
intensity: 1
frequency: 30
subframes:
  - _target_: run_stages.pattern_generation_stage.Subframe
    duration_ms: ${duration}
    patterns:
      - _target_: run_stages.pattern_generation_stage.Text
        text: "C"
        gap_size: 6
  - _target_: run_stages.pattern_generation_stage.Subframe
    duration_ms: "${eval: '1 / ${frequency} * 1000 - ${duration}'}"
    patterns:
      - _target_: run_stages.pattern_generation_stage.FullField
        fill_color: "black"

list_of_frames:
  - _target_: run_stages.pattern_generation_stage.Frame
    name: "Landolt_C_PS20"
    repetitions: 1
    subframes: ${subframes}

list_projections:
  - _target_: run_stages.pattern_generation_stage.ProjectionSequence
    intensity_mW_mm2: ${intensity}
    frequency_Hz: ${frequency}
    frames: ${list_of_frames}

video_sequence_name:
  - "Landolt_C_PS100_${frequency}Hz_2"

    
